# Site settings
name: My Blog
email:
author: Tetyana Shevchuk

keywords: jekyll
description: > # this means to ignore newlines until "baseurl:"
  Witty description here.
baseurl: ""
url: https://frostdragon.github.io

header: yes
header_sm: images/banner-small.jpg
header_med: images/banner-med.jpg
header_large: images/banner-large.jpg
header_xl: images/banner-xl.jpg

destination: _site
#permalink: /blog/:year/:title
paginate: 2
paginate_path: "/blog/page:num"

sass:
  sass_dir: _sass
  style: :compressed

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Rohan Chandra
  avatar:
  description: "My blog on Github" # used by search engines

  # Header and footer text
  header_text:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Читати далі"
