# Site settings
name: My Blog
email:
author: Tetyana Shevchuk

keywords: jekyll
description: > # this means to ignore newlines until "baseurl:"
  Witty description here.
baseurl: ""
url: https://frostdragon.github.io

header: yes
header_sm: images/banner-small.jpg
header_med: images/banner-med.jpg
header_large: images/banner-large.jpg
header_xl: images/banner-xl.jpg

permalink: /blog/:year/:title
